slack:
  enabled: true
  bot_token: ${SLACK_BOT_TOKEN}
  app_token: ${SLACK_APP_TOKEN}
  # default_channel_id: C04ABC123
  # default_user_id: U04ABC123
  owner_user_id: ${OWNER_SLACK_USER_ID}

telegram:
  enabled: true
  bot_token: 8659031368:AAFXiEyrevuRZVhSljBC1cd0thm4Jkn7Dlw
